### ISSUE TITLE
Blynk Token on every node

### ISSUE THREAD

**Issue by mtrohman** [gablau/node-red-contrib-blynk-ws#4]
Hi, nice library, i've used it, but is it possible to put blynk token on every node so that we can use several blynk token without additional configuration node.

**Comment by gablau** [comment]
Hello,
no, it is not possible to insert the auth token in every node.
Commonly it would be a waste of resources, because it should open a socket for each node!
Now it works like this: 
the configuration node has the token, and at the start of nodered opens the socket and authenticates with the server, then the various nodes can send commands on that connection.
